# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, alex, happy, split, prettyShow }:

cabal.mkDerivation (self: {
  pname = "trinity";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ split prettyShow ];
  buildTools = [ alex happy ];
  meta = {
    homepage = "http://ldc.usb.ve/~05-38235/cursos/CI3725/2014SD/";
    description = "Lenguaje de programación para el proyecto de CI3725 (Traductores e interpretadores) en Septiembre–Diciembre de 2014 en la Universidad Simón Bolívar";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
